DECLARE
    L_NAME VARCHAR2(25);
    F_NAME VARCHAR2(25);
BEGIN
    L_NAME := '&LAST_NAME';
    F_NAME := '&FIRST_NAME';
    INSERT INTO MY_EMPLOYEE VALUES(&ID,L_NAME,F_NAME,
        LOWER(SUBSTR(F_NAME,1,1)||SUBSTR(L_NAME,1,7)),&SALARY);
END;